### model
model_name_or_path: /home/nsarkar/orcd/pool/GPTeacher/model_checkpoints/qwen3_0-6B_adversarial_7
do_train: true
do_eval: false

### method
stage: sft
finetuning_type: full
# finetuning_type: lora
# lora_rank: 16
# lora_target: all
gradient_checkpointing: true
deepspeed: ./examples/deepspeed/ds_z3_config.json

### dataset
dataset: adversarial_dataset_8
template: qwen
cutoff_len: 32768
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: ../model_checkpoints/qwen3_0-6B_adversarial_8
logging_steps: 1
save_strategy: steps
save_steps: 200
plot_loss: true
overwrite_output_dir: true
report_to: wandb  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 8
learning_rate: 1.0e-5
lr_scheduler_type: cosine
num_train_epochs: 1
warmup_ratio: 0.05
weight_decay: 0
adam_beta1: 0.9
adam_beta2: 0.95
max_steps: -1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval
# eval_dataset: val_dataset
# per_device_eval_batch_size: 2
# eval_strategy: epoch
# eval_steps: 100 
